# Generated by Django 4.2.11 on 2025-03-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_room_options_remove_room_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='participant_count',
            field=models.IntegerField(default=1, help_text='Number of participants'),
        ),
    ]
