# Generated by Django 5.1.7 on 2025-03-22 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_reservation_participant_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.reservation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
