# Generated by Django 5.2 on 2025-05-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(unique=True)),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True, help_text='فعال بودن اسلات برای نمایش در فرم\u200cها')),
            ],
            options={
                'ordering': ['start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_after_start_time')],
            },
        ),
    ]
